[profile.default]
src = "contracts"
test = "test"
out = "out"
libs = ["lib", "node_modules"]
solc_version = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = false

remappings = [
  "@openzeppelin/=node_modules/@openzeppelin/",
  "forge-std/=lib/forge-std/src/"
]
